# Primeiros passos com NumPy — Turma 5

Um guia para quem está começando: explicações, exemplos pequenos e **20 exercícios com resolução comentada**.

## Como usar este notebook

1. Abra este arquivo `.ipynb` no VS Code e selecione o kernel Python no canto superior direito.
2. Leia o texto antes de executar o código.
3. Execute as células de cima para baixo usando o ▶ ao lado de cada célula.
4. Antes de executar, tente prever o resultado.
5. Nos exercícios, escreva sua tentativa antes de olhar a resolução.

Uma **célula de texto** explica. Uma **célula de código** é executada pelo Python. O **kernel** é o processo que executa esse código e guarda as variáveis. Se você reiniciar o kernel, execute novamente as células anteriores.

Não precisamos baixar dados ou fazer gráficos.

### Se o NumPy não estiver instalado

Execute a célula opcional abaixo retirando o `#` da primeira linha. `%pip` instala o pacote no ambiente do kernel do notebook. Depois, se necessário, reinicie o kernel e execute as células novamente.


In [1]:
# %pip install numpy
# Execute esta instalação somente se aparecer ModuleNotFoundError ao importar numpy.

## 1. O que é NumPy?

**NumPy é uma biblioteca do Python para trabalhar com números e arrays.** Uma biblioteca reúne ferramentas prontas que podemos usar no nosso programa.

Um **array** é uma estrutura que guarda vários valores. Neste início, pense nele como uma sequência de números na qual podemos aplicar cálculos a todos os elementos de uma vez. Também podemos criar arrays com linhas e colunas.

Em um array comum do NumPy, os elementos compartilham um tipo de dado (`dtype`). Uma lista Python pode misturar tipos livremente; um array numérico é organizado para cálculos.

`import numpy as np` importa a biblioteca e dá a ela o apelido `np`. Esse apelido é uma convenção: não cria outra biblioteca.

In [2]:
import numpy as np

print("NumPy importado!")

NumPy importado!


Se apareceu a mensagem, podemos usar os comandos que começam com `np`.

### Para que NumPy é bom?

NumPy ajuda quando precisamos **fazer cálculos com muitos números seguindo a mesma regra**. Podemos escrever uma operação para o conjunto inteiro, em vez de escrever um cálculo separado para cada valor.

| Situação | Como NumPy ajuda |
|---|---|
| Preços de uma loja | Aplicar desconto ou aumento a todos os preços |
| Compras | Multiplicar preços por quantidades e somar o total |
| Notas de uma turma | Calcular média, mínimo, máximo e selecionar notas |
| Medições | Calcular e comparar conjuntos de temperaturas ou distâncias |
| Imagens | Representar os valores dos pixels em arrays e fazer cálculos sobre eles |
| Machine learning | Representar características numéricas e trabalhar com vetores e matrizes |

**Exemplo concreto:** uma loja quer dar 10% de desconto em três preços. Com 10% de desconto, pagamos 90% do preço: multiplicamos por `0.90`.


In [3]:
precos_desconto = np.array([100, 200, 50])
precos_com_desconto = precos_desconto * 0.90

print("Antes:", precos_desconto)
print("Com 10% de desconto:", precos_com_desconto)


Antes: [100 200  50]
Com 10% de desconto: [ 90. 180.  45.]


O resultado é `[90. 180. 45.]`. Uma operação aplica a mesma regra aos três preços. O array original continua com 100, 200 e 50.

**Por que usar?** O código expressa o cálculo de forma curta e as operações numéricas do NumPy costumam ser eficientes para grandes arrays. Isso não significa que qualquer programa ficará mais rápido só por importar a biblioteca.

**Quando uma lista já resolve?** Para guardar nomes, organizar poucos itens ou acrescentar e remover elementos com frequência, uma lista Python pode ser suficiente.

**E o pandas?** Pandas é conveniente para tabelas com nomes de colunas, como nome, idade e cidade. NumPy se concentra em arrays e cálculos numéricos. As duas bibliotecas podem ser usadas juntas; não precisamos escolher uma para todas as tarefas.


## 2. Criar um array e ler os símbolos

Vamos guardar três preços em um array.

| Trecho | Significado |
|---|---|
| `precos` | Nome da variável que guardará o array |
| `=` | Atribui o resultado à variável; não é uma pergunta de igualdade |
| `np` | Apelido da biblioteca NumPy |
| `.` | Acessa algo que pertence à biblioteca ou ao objeto |
| `array` | Função que cria um array |
| `(...)` | Chama a função e recebe seus argumentos |
| `[10, 20, 30]` | Lista Python passada como argumento |
| `,` | Separa os elementos |

**Argumento** é o valor fornecido na chamada. Aqui, a lista `[10, 20, 30]` é o argumento de `np.array`.

In [4]:
precos = np.array([10, 20, 30])
print(precos)
print(type(precos))

[10 20 30]
<class 'numpy.ndarray'>


A primeira linha impressa é `[10 20 30]`. O NumPy costuma mostrar arrays sem vírgulas. O objeto continua tendo três elementos.

`type(precos)` informa o tipo do objeto: `numpy.ndarray`, o tipo de array do NumPy.

## 3. Lista Python × array NumPy

O símbolo `*` pode ter efeitos diferentes conforme o tipo do objeto. Em uma lista, multiplicar por 2 repete a sequência. Em um array numérico, multiplica cada elemento por 2.

### O que uma lista e um array têm em comum?

Você já conhece listas? Então já conhece várias ideias que também usaremos com arrays! **Os dois podem guardar vários valores em uma sequência ordenada.** Ordenada significa que cada elemento tem uma posição; não significa que os valores estejam do menor para o maior.

Vamos representar os mesmos três preços de duas maneiras:

| Semelhança | Lista Python | Array NumPy |
|---|---|---|
| Guarda vários valores | `[10, 20, 30]` | `np.array([10, 20, 30])` |
| Primeiro índice é zero | `lista_precos[0]` | `array_precos[0]` |
| Pode acessar o último com -1 | `lista_precos[-1]` | `array_precos[-1]` |
| Permite selecionar trechos | `lista_precos[0:2]` | `array_precos[0:2]` |
| Pode consultar o tamanho | `len(lista_precos)` | `len(array_precos)` |
| Permite percorrer com for | `for preco in lista_precos:` | `for preco in array_precos:` |
| Permite alterar um elemento | `lista_precos[0] = 15` | `array_precos[0] = 15` |

Aqui usamos um array de **uma dimensão**. Nesse caso, `len` informa a quantidade de elementos. Em um array de duas dimensões, `len` informa o tamanho da primeira dimensão, enquanto `.size` informa o total de elementos.


In [5]:
lista_precos = [10, 20, 30]
array_precos = np.array(lista_precos)

print("Lista:", lista_precos)
print("Array:", array_precos)
print("Primeiro da lista:", lista_precos[0])
print("Primeiro do array:", array_precos[0])
print("Último da lista:", lista_precos[-1])
print("Último do array:", array_precos[-1])
print("Trecho da lista:", lista_precos[0:2])
print("Trecho do array:", array_precos[0:2])
print("Tamanho da lista:", len(lista_precos))
print("Tamanho do array:", len(array_precos))

Lista: [10, 20, 30]
Array: [10 20 30]
Primeiro da lista: 10
Primeiro do array: 10
Último da lista: 30
Último do array: 30
Trecho da lista: [10, 20]
Trecho do array: [10 20]
Tamanho da lista: 3
Tamanho do array: 3


**Leia o código:** `lista_precos[0]` e `array_precos[0]` usam a mesma ideia: acessar o valor da primeira posição. Nos dois, `[0:2]` seleciona os índices 0 e 1; o índice 2 fica de fora.

Os resultados têm os mesmos valores, mas os objetos são de tipos diferentes. As vírgulas aparecem na impressão da lista; normalmente não aparecem na impressão do array.

Também podemos usar `for` para visitar um valor por vez nos dois objetos.

In [6]:
print("Percorrendo a lista:")
for preco in lista_precos:
    print(preco)

print("Percorrendo o array:")
for preco in array_precos:
    print(preco)

Percorrendo a lista:
10
20
30
Percorrendo o array:
10
20
30


`preco` recebe um elemento por vez: primeiro 10, depois 20 e depois 30. O bloco com recuo é executado uma vez para cada elemento.

Os dois também permitem alterar um valor por posição:

In [7]:
lista_precos[0] = 15
array_precos[0] = 15

print("Lista alterada:", lista_precos)
print("Array alterado:", array_precos)

Lista alterada: [15, 20, 30]
Array alterado: [15 20 30]


Agora os dois contêm 15, 20 e 30. Estamos alterando um elemento que já existe, não acrescentando um novo.

### Semelhanças não significam comportamento idêntico

- **Cálculos:** lista multiplicada por 2 repete os elementos; array numérico multiplicado por 2 dobra cada valor. Vamos conferir isso no exemplo seguinte.
- **Tipos:** uma lista pode misturar tipos; os elementos de um array comum compartilham um `dtype`. Ao criar um array com tipos diferentes, o NumPy pode converter os valores para um tipo comum.
- **Acrescentar:** listas têm `.append()`. Arrays NumPy não têm esse método; `np.append` cria um novo array com os valores acrescentados.
- **Fatiamento:** um trecho de lista cria uma nova lista superficial. Um fatiamento simples de array geralmente compartilha os dados com o original. Para editar o trecho de array de forma independente, use `.copy()`, explicado mais adiante.

**Pergunta para conferir:** se os valores são `[10, 20, 30]`, o que `[1]` seleciona em cada estrutura? **20 nos dois casos**, pois a contagem começa em zero.


In [8]:
lista = [10, 20, 30]
array = np.array(lista)

print("Lista vezes 2:", lista * 2)
print("Array vezes 2:", array * 2)

Lista vezes 2: [10, 20, 30, 10, 20, 30]
Array vezes 2: [20 40 60]


A lista resulta em `[10, 20, 30, 10, 20, 30]`. O array resulta em `[20 40 60]`. Por isso precisamos observar o tipo do dado antes de prever o cálculo.

## 4. Atributo, função e método

**Atributo** é uma informação do objeto: usamos sem parênteses, como `precos.size`.

**Função** é uma operação que chamamos com parênteses, como `np.sum(precos)`.

**Método** é uma operação acessada pelo próprio objeto, como `precos.sum()`.

**Parâmetro** é o nome de uma entrada na definição de uma função; **argumento** é o valor passado na chamada. **Retorno** é o resultado que a chamada entrega para ser usado ou guardado.

| Expressão | O que informa |
|---|---|
| `precos.ndim` | Número de dimensões |
| `precos.shape` | Tamanho de cada dimensão |
| `precos.size` | Total de elementos |
| `precos.dtype` | Tipo dos elementos |

In [9]:
print("Dimensões:", precos.ndim)
print("Formato:", precos.shape)
print("Elementos:", precos.size)
print("Tipo dos elementos:", precos.dtype)

print("Soma com função:", np.sum(precos))
print("Soma com método:", precos.sum())

Dimensões: 1
Formato: (3,)
Elementos: 3
Tipo dos elementos: int64
Soma com função: 60
Soma com método: 60


Este array tem uma dimensão, formato `(3,)` e três elementos. `(3,)` é uma tupla com um único tamanho: 3. A vírgula faz parte da escrita de uma tupla de um elemento.

O tipo inteiro exibido pode variar conforme o ambiente. As duas formas de somar devolvem 60.

`precos.sum` sem `()` acessa o método, mas não executa a soma. `precos.size()` tentaria chamar um número e causaria erro: `size` é atributo.

## 5. Acessar elementos com índices

Um **índice** indica a posição de um elemento. Em Python, a primeira posição é **0**. Os colchetes agora acessam elementos; na criação do array, eles formavam uma lista.

In [10]:
idades = np.array([18, 25, 32, 40])

print("Primeiro:", idades[0])
print("Segundo:", idades[1])
print("Último:", idades[-1])

Primeiro: 18
Segundo: 25
Último: 40


`idades[0]` devolve 18; `idades[1]` devolve 25; `idades[-1]` devolve 40. O índice negativo -1 conta a partir do final. `idades[4]` causaria erro, pois os índices válidos positivos são 0, 1, 2 e 3.

## 6. Selecionar um trecho: fatiamento

O fatiamento seleciona um trecho: `array[início:fim]`. **O início entra; o fim não entra.**

Em `idades[1:3]`, selecionamos os índices 1 e 2. Se omitirmos o início, começamos no primeiro elemento; se omitirmos o fim, vamos até o final.

In [11]:
print("Índices 1 e 2:", idades[1:3])
print("Do começo até antes do índice 2:", idades[:2])
print("Do índice 2 até o final:", idades[2:])

Índices 1 e 2: [25 32]
Do começo até antes do índice 2: [18 25]
Do índice 2 até o final: [32 40]


Os resultados são `[25 32]`, `[18 25]` e `[32 40]`, respectivamente.

## 7. Calcular com todos os elementos

Podemos somar, subtrair, multiplicar ou dividir cada elemento por um número. Esse cálculo por elemento costuma evitar um `for` escrito por nós.

A operação abaixo produz um novo resultado; guardar em outra variável mantém o array original neste exemplo.

In [12]:
valores = np.array([10, 20, 30])

print("Mais 5:", valores + 5)
print("Menos 2:", valores - 2)
print("Dobro:", valores * 2)
print("Metade:", valores / 2)

valores_com_aumento = valores + 5
print("Original:", valores)
print("Com aumento:", valores_com_aumento)

Mais 5: [15 25 35]
Menos 2: [ 8 18 28]
Dobro: [20 40 60]
Metade: [ 5. 10. 15.]
Original: [10 20 30]
Com aumento: [15 25 35]


Os resultados são `[15 25 35]`, `[8 18 28]`, `[20 40 60]` e `[5. 10. 15.]`. A divisão `/` produz números com parte decimal. O ponto em `5.` indica 5.0.

## 8. Operações entre dois arrays

Para este exemplo, cada preço tem uma quantidade correspondente. Como os dois arrays têm o mesmo formato, a multiplicação combina os elementos pela posição.

In [13]:
precos_compra = np.array([10, 20, 5])
quantidades = np.array([2, 3, 4])

subtotais = precos_compra * quantidades
print("Subtotais:", subtotais)
print("Total da compra:", subtotais.sum())

Subtotais: [20 60 20]
Total da compra: 100


O cálculo é 10 × 2, 20 × 3 e 5 × 4: `[20 60 20]`. A soma é 100. Não é multiplicação de matrizes. Outros formatos exigem regras de compatibilidade; aqui usamos arrays iguais para manter o exemplo simples.

## 9. Somar, calcular média, mínimo e máximo

Estas funções resumem um conjunto de números.

| Função | Uso |
|---|---|
| `np.sum` | Soma |
| `np.mean` | Média aritmética |
| `np.min` | Menor valor |
| `np.max` | Maior valor |

A média é a soma dividida pela quantidade de valores.

In [14]:
notas = np.array([6, 8, 10])

print("Soma:", np.sum(notas))
print("Média:", np.mean(notas))
print("Menor:", np.min(notas))
print("Maior:", np.max(notas))

Soma: 24
Média: 8.0
Menor: 6
Maior: 10


A soma é 24; a média é 24 ÷ 3 = 8.0; o mínimo é 6 e o máximo é 10.

## 10. Comparações e filtros

`>=` significa maior ou igual. A comparação abaixo devolve um array de valores **booleanos**: `True` significa verdadeiro; `False`, falso.

Essa sequência é uma **máscara**: ao colocá-la entre colchetes, selecionamos apenas os elementos marcados com `True`.

In [15]:
idades_filtro = np.array([18, 25, 32, 40])
mascara = idades_filtro >= 25

print("Condição:", mascara)
selecionadas = idades_filtro[mascara]
print("Selecionadas:", selecionadas)

# A mesma seleção em uma linha:
print(idades_filtro[idades_filtro >= 25])

Condição: [False  True  True  True]
Selecionadas: [25 32 40]
[25 32 40]


A máscara é `[False True True True]`. O filtro devolve `[25 32 40]`. A idade 25 entra porque usamos `>=`, e não apenas `>`.

## 11. Escolher um resultado com np.where

`np.where(condição, valor_se_verdadeiro, valor_se_falso)` escolhe um resultado para cada posição.

Vamos aplicar a regra: nota maior ou igual a 7 recebe `"Aprovado"`; caso contrário, recebe `"Revisar"`. As aspas indicam texto.

In [16]:
notas_status = np.array([6, 7, 9])
status = np.where(notas_status >= 7, "Aprovado", "Revisar")

print(status)

['Revisar' 'Aprovado' 'Aprovado']


O resultado é `['Revisar' 'Aprovado' 'Aprovado']`. O 7 atende à condição porque o limite está incluído. `np.where` devolve um novo array; não altera as notas.

## 12. Criar sequências e ordenar

`np.arange(início, fim, passo)` cria uma sequência. O início entra e o fim não entra. O passo informa quanto avançamos.

`np.sort(array)` devolve os valores em ordem crescente.

In [17]:
sequencia = np.arange(0, 10, 2)
print("Sequência:", sequencia)

valores_fora_de_ordem = np.array([30, 10, 20])
ordenados = np.sort(valores_fora_de_ordem)
print("Ordenados:", ordenados)
print("Original:", valores_fora_de_ordem)

Sequência: [0 2 4 6 8]
Ordenados: [10 20 30]
Original: [30 10 20]


A sequência é `[0 2 4 6 8]`: o 10 não entra. A ordenação devolve `[10 20 30]`. `np.sort` mantém o array original neste exemplo.

## 13. Arrays com linhas e colunas

Um array de duas dimensões pode ser visto como uma grade. Cada lista interna representa uma linha.

`matriz[linha, coluna]` seleciona uma posição; ambas as contagens começam em zero. `:` significa selecionar todos os elementos daquela dimensão.

In [18]:
matriz = np.array([[10, 20], [30, 40]])
print(matriz)
print("Formato:", matriz.shape)
print("Dimensões:", matriz.ndim)
print("Elementos:", matriz.size)
print("Linha 0, coluna 1:", matriz[0, 1])
print("Primeira linha:", matriz[0, :])
print("Primeira coluna:", matriz[:, 0])

[[10 20]
 [30 40]]
Formato: (2, 2)
Dimensões: 2
Elementos: 4
Linha 0, coluna 1: 20
Primeira linha: [10 20]
Primeira coluna: [10 30]


A matriz tem formato `(2, 2)`, duas dimensões e quatro elementos. A posição `[0, 1]` contém 20. A primeira linha é `[10 20]` e a primeira coluna é `[10 30]`.

## 14. Cuidado ao copiar um array

`copia = original` cria outro nome para o mesmo objeto. Para ter um array independente neste exemplo, use `original.copy()`.

Fatiamentos simples de arrays NumPy geralmente também compartilham dados com o original. Se você pretende editar o trecho sem alterar o original, use `.copy()`.

In [19]:
original = np.array([10, 20, 30])
copia_independente = original.copy()
copia_independente[0] = 99

print("Original:", original)
print("Cópia:", copia_independente)

Original: [10 20 30]
Cópia: [99 20 30]


A cópia fica `[99 20 30]`; o original continua `[10 20 30]`. A atribuição com `[0] = 99` altera o elemento da primeira posição na cópia.

## 15. Sua vez — 20 exercícios

Siga nosso roteiro em cada exercício:

1. **Entender:** o que foi pedido?
2. **Identificar:** quais dados e qual regra serão usados?
3. **Resolver à mão:** que resultado esperamos?
4. **Planejar:** qual comando atende ao pedido?
5. **Executar:** escrever e rodar o código.
6. **Conferir:** comparar com o resultado esperado.

As resoluções estão em uma seção separada ao final. Cada exercício tem seus próprios dados: execute a célula de preparação e depois escreva sua tentativa.


### Exercício 1 — Criar um array

**Pedido:** Crie um array com os preços 12, 18 e 30. Guarde em `precos_ex1` e mostre na tela.

**Resultado esperado:** `[12 18 30]`

In [20]:
# Escreva sua tentativa abaixo.


### Exercício 2 — Consultar as posições

**Pedido:** Mostre o primeiro e o último valor de `idades_ex2`.

**Resultado esperado:** `19 e 42`

In [21]:
idades_ex2 = np.array([19, 24, 31, 42])

In [22]:
# Escreva sua tentativa abaixo.


### Exercício 3 — Selecionar um trecho

**Pedido:** Selecione somente 15 e 20 usando fatiamento.

**Resultado esperado:** `[15 20]`

In [23]:
valores_ex3 = np.array([5, 10, 15, 20, 25])

In [24]:
# Escreva sua tentativa abaixo.


### Exercício 4 — Aumentar os preços

**Pedido:** Some 5 a cada preço e guarde em `novos_precos_ex4`.

**Resultado esperado:** `[15 25 35]`

In [25]:
precos_ex4 = np.array([10, 20, 30])

In [26]:
# Escreva sua tentativa abaixo.


### Exercício 5 — Calcular uma compra

**Pedido:** Multiplique os preços pelas quantidades correspondentes. Mostre os subtotais e o total.

**Resultado esperado:** `Subtotais: [16 30 30]; total: 76`

In [27]:
precos_ex5 = np.array([8, 15, 10])
quantidades_ex5 = np.array([2, 2, 3])

In [28]:
# Escreva sua tentativa abaixo.


### Exercício 6 — Resumir notas

**Pedido:** Mostre a média, a menor nota e a maior nota.

**Resultado esperado:** `Média: 7.0; menor: 5; maior: 9`

In [29]:
notas_ex6 = np.array([5, 7, 9])

In [30]:
# Escreva sua tentativa abaixo.


### Exercício 7 — Filtrar idades

**Pedido:** Selecione apenas as idades maiores ou iguais a 25.

**Resultado esperado:** `[25 27 40]`

In [31]:
idades_ex7 = np.array([18, 25, 27, 22, 40])

In [32]:
# Escreva sua tentativa abaixo.


### Exercício 8 — Indicar reposição

**Pedido:** Use np.where: estoque menor que 10 recebe "Repor"; caso contrário, "Normal".

**Resultado esperado:** `['Repor' 'Normal' 'Normal' 'Repor']`

In [33]:
estoques_ex8 = np.array([5, 10, 12, 3])

In [34]:
# Escreva sua tentativa abaixo.


### Exercício 9 — Criar uma sequência

**Pedido:** Use np.arange para criar os números pares de 2 a 10, incluindo o 10.

**Resultado esperado:** `[2 4 6 8 10]`

In [35]:
# Escreva sua tentativa abaixo.


### Exercício 10 — Ler uma matriz

**Pedido:** Mostre o formato da matriz e o valor que está na segunda linha, terceira coluna.

**Resultado esperado:** `Formato: (2, 3); valor: 6`

In [36]:
matriz_ex10 = np.array([[1, 2, 3], [4, 5, 6]])

In [37]:
# Escreva sua tentativa abaixo.


### Exercício 11 — Somar vendas

**Pedido:** Calcule o total das vendas dos quatro dias.

**Resultado esperado:** `500`

In [38]:
vendas_ex11 = np.array([100, 150, 80, 170])

In [39]:
# Escreva sua tentativa abaixo.


### Exercício 12 — Aplicar um desconto

**Pedido:** Dê 10% de desconto a cada preço e guarde os novos valores.

**Resultado esperado:** `[45. 90. 180.]`

In [40]:
precos_ex12 = np.array([50, 100, 200])

In [41]:
# Escreva sua tentativa abaixo.


### Exercício 13 — Comparar duas semanas

**Pedido:** Calcule a diferença segunda semana menos primeira semana para cada produto.

**Resultado esperado:** `[2 -2 5]`

In [42]:
semana1_ex13 = np.array([10, 20, 15])
semana2_ex13 = np.array([12, 18, 20])

In [43]:
# Escreva sua tentativa abaixo.


### Exercício 14 — Mostrar a máscara

**Pedido:** Crie e mostre a máscara que indica quais notas são maiores ou iguais a 7. Neste exercício, não filtre as notas.

**Resultado esperado:** `[False True True False]`

In [44]:
notas_ex14 = np.array([5, 7, 8, 6])

In [45]:
# Escreva sua tentativa abaixo.


### Exercício 15 — Contar aprovações

**Pedido:** Conte quantas notas são maiores ou iguais a 7. Dica: np.sum pode somar uma máscara booleana; cada True conta como 1 e cada False como 0.

**Resultado esperado:** `3`

In [46]:
notas_ex15 = np.array([6, 7, 9, 4, 8])

In [47]:
# Escreva sua tentativa abaixo.


### Exercício 16 — Filtrar valores abaixo do limite

**Pedido:** Selecione apenas os preços menores que 50. O preço 50 não deve entrar.

**Resultado esperado:** `[25 40 10]`

In [48]:
precos_ex16 = np.array([25, 50, 80, 40, 10])

In [49]:
# Escreva sua tentativa abaixo.


### Exercício 17 — Ordenar os valores

**Pedido:** Guarde os valores em ordem crescente em uma nova variável e mostre também o array original.

**Resultado esperado:** `Ordenados: [10 20 30 45]; original: [45 10 30 20]`

In [50]:
valores_ex17 = np.array([45, 10, 30, 20])

In [51]:
# Escreva sua tentativa abaixo.


### Exercício 18 — Copiar e alterar

**Pedido:** Faça uma cópia independente de estoques_ex18. Na cópia, altere o primeiro estoque para 99. Mostre os dois arrays.

**Resultado esperado:** `Original: [5 10 15]; cópia: [99 10 15]`

In [52]:
estoques_ex18 = np.array([5, 10, 15])

In [53]:
# Escreva sua tentativa abaixo.


### Exercício 19 — Selecionar uma coluna

**Pedido:** Cada linha representa uma loja; as colunas representam segunda, terça e quarta. Selecione os valores da terça-feira de todas as lojas e calcule o total dessa coluna.

**Resultado esperado:** `Terça: [20 25]; total: 45`

In [54]:
vendas_ex19 = np.array([[10, 20, 30], [15, 25, 35]])

In [55]:
# Escreva sua tentativa abaixo.


### Exercício 20 — Desafio: analisar uma compra

**Pedido:** Calcule os subtotais (preço × quantidade), o total da compra e a média dos subtotais. Depois use np.where para marcar cada subtotal: maior ou igual a 30 recebe "Alto"; caso contrário, "Baixo".

**Resultado esperado:** `Subtotais: [20 45 20]; total: 85; média: aproximadamente 28.33; rótulos: Baixo, Alto, Baixo`

In [56]:
precos_ex20 = np.array([10, 15, 5])
quantidades_ex20 = np.array([2, 3, 4])

In [57]:
# Escreva sua tentativa abaixo.


## 16. Resoluções comentadas

Compare a sua tentativa com cada resolução. Se o resultado for diferente, confira o operador, os índices e o nome das variáveis.

### Resolução 1 — Criar um array

np.array recebe a lista de preços. A variável guarda o array e print o mostra.

In [58]:
precos_ex1 = np.array([12, 18, 30])
print(precos_ex1)

[12 18 30]


### Resolução 2 — Consultar as posições

O índice 0 seleciona o primeiro elemento; -1 seleciona o último.

In [59]:
idades_ex2 = np.array([19, 24, 31, 42])

print(idades_ex2[0])
print(idades_ex2[-1])

19
42


### Resolução 3 — Selecionar um trecho

15 está no índice 2 e 20 no índice 3. O limite final 4 fica de fora.

In [60]:
valores_ex3 = np.array([5, 10, 15, 20, 25])

trecho_ex3 = valores_ex3[2:4]
print(trecho_ex3)

[15 20]


### Resolução 4 — Aumentar os preços

A soma com um número é aplicada a cada elemento. A variável recebe o novo array.

In [61]:
precos_ex4 = np.array([10, 20, 30])

novos_precos_ex4 = precos_ex4 + 5
print(novos_precos_ex4)

[15 25 35]


### Resolução 5 — Calcular uma compra

Os produtos são 8 × 2, 15 × 2 e 10 × 3. A soma reúne os três subtotais.

In [62]:
precos_ex5 = np.array([8, 15, 10])
quantidades_ex5 = np.array([2, 2, 3])

subtotais_ex5 = precos_ex5 * quantidades_ex5
print(subtotais_ex5)
print(np.sum(subtotais_ex5))

[16 30 30]
76


### Resolução 6 — Resumir notas

A média é (5 + 7 + 9) ÷ 3. min encontra o menor elemento; max, o maior.

In [63]:
notas_ex6 = np.array([5, 7, 9])

print(np.mean(notas_ex6))
print(np.min(notas_ex6))
print(np.max(notas_ex6))

7.0
5
9


### Resolução 7 — Filtrar idades

A comparação cria a máscara. Os colchetes usam a máscara para selecionar os valores que atendem à regra.

In [64]:
idades_ex7 = np.array([18, 25, 27, 22, 40])

mascara_ex7 = idades_ex7 >= 25
resultado_ex7 = idades_ex7[mascara_ex7]
print(resultado_ex7)

[25 27 40]


### Resolução 8 — Indicar reposição

5 e 3 são menores que 10. O estoque 10 recebe Normal, pois a condição usa < e não <=.

In [65]:
estoques_ex8 = np.array([5, 10, 12, 3])

status_ex8 = np.where(estoques_ex8 < 10, "Repor", "Normal")
print(status_ex8)

['Repor' 'Normal' 'Normal' 'Repor']


### Resolução 9 — Criar uma sequência

Começamos em 2 e avançamos de 2 em 2. Usamos o limite 11 para que o 10 entre; o limite final é excluído.

In [66]:
pares_ex9 = np.arange(2, 11, 2)
print(pares_ex9)

[ 2  4  6  8 10]


### Resolução 10 — Ler uma matriz

Há duas linhas e três colunas. A segunda linha tem índice 1 e a terceira coluna tem índice 2.

In [67]:
matriz_ex10 = np.array([[1, 2, 3], [4, 5, 6]])

print(matriz_ex10.shape)
print(matriz_ex10[1, 2])

(2, 3)
6


### Resolução 11 — Somar vendas

sum soma todos os valores: 100 + 150 + 80 + 170 = 500.

In [68]:
vendas_ex11 = np.array([100, 150, 80, 170])

total_ex11 = np.sum(vendas_ex11)
print(total_ex11)

500


### Resolução 12 — Aplicar um desconto

Depois de descontar 10%, restam 90% do preço. Multiplicamos cada valor por 0.90.

In [69]:
precos_ex12 = np.array([50, 100, 200])

desconto_ex12 = precos_ex12 * 0.90
print(desconto_ex12)

[ 45.  90. 180.]


### Resolução 13 — Comparar duas semanas

A subtração combina as posições correspondentes. -2 indica que a venda do segundo produto diminuiu em duas unidades.

In [70]:
semana1_ex13 = np.array([10, 20, 15])
semana2_ex13 = np.array([12, 18, 20])

diferenca_ex13 = semana2_ex13 - semana1_ex13
print(diferenca_ex13)

[ 2 -2  5]


### Resolução 14 — Mostrar a máscara

A comparação devolve um booleano por posição. 7 e 8 atendem à condição; 5 e 6 não.

In [71]:
notas_ex14 = np.array([5, 7, 8, 6])

mascara_ex14 = notas_ex14 >= 7
print(mascara_ex14)

[False  True  True False]


### Resolução 15 — Contar aprovações

A máscara tem três True, referentes às notas 7, 9 e 8. Sua soma é 3.

In [72]:
notas_ex15 = np.array([6, 7, 9, 4, 8])

aprovacoes_ex15 = notas_ex15 >= 7
quantidade_ex15 = np.sum(aprovacoes_ex15)
print(quantidade_ex15)

3


### Resolução 16 — Filtrar valores abaixo do limite

Usamos <, pois o limite não entra. O filtro preserva a ordem dos elementos selecionados; não os ordena.

In [73]:
precos_ex16 = np.array([25, 50, 80, 40, 10])

baratos_ex16 = precos_ex16[precos_ex16 < 50]
print(baratos_ex16)

[25 40 10]


### Resolução 17 — Ordenar os valores

np.sort devolve um array ordenado. Ao guardar esse resultado em outra variável, mantemos o original.

In [74]:
valores_ex17 = np.array([45, 10, 30, 20])

ordenados_ex17 = np.sort(valores_ex17)
print("Ordenados:", ordenados_ex17)
print("Original:", valores_ex17)

Ordenados: [10 20 30 45]
Original: [45 10 30 20]


### Resolução 18 — Copiar e alterar

copy cria um array independente. O índice 0 identifica o primeiro elemento; a atribuição altera somente a cópia.

In [75]:
estoques_ex18 = np.array([5, 10, 15])

copia_ex18 = estoques_ex18.copy()
copia_ex18[0] = 99
print("Original:", estoques_ex18)
print("Cópia:", copia_ex18)

Original: [ 5 10 15]
Cópia: [99 10 15]


### Resolução 19 — Selecionar uma coluna

Em [:, 1], : seleciona todas as linhas e 1 seleciona a segunda coluna. 20 + 25 = 45.

In [76]:
vendas_ex19 = np.array([[10, 20, 30], [15, 25, 35]])

terca_ex19 = vendas_ex19[:, 1]
print("Terça:", terca_ex19)
print("Total:", np.sum(terca_ex19))

Terça: [20 25]
Total: 45


### Resolução 20 — Desafio: analisar uma compra

Primeiro multiplicamos por posição. Depois resumimos os subtotais com sum e mean. A média é 85 ÷ 3 e pode aparecer com várias casas decimais. where atribui os rótulos; somente 45 atende ao limite.

In [77]:
precos_ex20 = np.array([10, 15, 5])
quantidades_ex20 = np.array([2, 3, 4])

subtotais_ex20 = precos_ex20 * quantidades_ex20
total_ex20 = np.sum(subtotais_ex20)
media_ex20 = np.mean(subtotais_ex20)
rotulos_ex20 = np.where(subtotais_ex20 >= 30, "Alto", "Baixo")
print("Subtotais:", subtotais_ex20)
print("Total:", total_ex20)
print("Média:", media_ex20)
print("Rótulos:", rotulos_ex20)

Subtotais: [20 45 20]
Total: 85
Média: 28.333333333333332
Rótulos: ['Baixo' 'Alto' 'Baixo']


## 17. Erros comuns e como conferir

| Situação | O que conferir |
|---|---|
| `ModuleNotFoundError: No module named 'numpy'` | Instale NumPy usando a célula opcional e confira o kernel selecionado |
| `NameError` | Execute a importação e a célula que criou a variável; confira a grafia |
| `IndexError` | A posição existe? Os índices começam em 0 |
| `SyntaxError` | Confira aspas, vírgulas, parênteses e colchetes |
| `TypeError` ao usar `array.size()` | size é atributo: use `array.size` |
| Aparece uma descrição do método em vez da soma | Use `array.sum()` com parênteses |
| `ValueError` ao calcular com arrays | Confira os formatos; nos nossos exemplos, os arrays correspondentes têm o mesmo shape |
| O filtro mostra apenas True e False | Use a máscara dentro dos colchetes do array para selecionar valores |

## 18. Consulta rápida

| Quero... | Exemplo |
|---|---|
| Criar um array | `np.array([10, 20, 30])` |
| Consultar o primeiro valor | `valores[0]` |
| Consultar o último | `valores[-1]` |
| Selecionar um trecho | `valores[1:3]` |
| Saber o formato | `valores.shape` |
| Saber quantos elementos há | `valores.size` |
| Multiplicar cada elemento por 2 | `valores * 2` |
| Somar os valores | `np.sum(valores)` |
| Calcular a média | `np.mean(valores)` |
| Filtrar valores maiores que 10 | `valores[valores > 10]` |
| Escolher entre dois resultados | `np.where(valores > 10, "Alto", "Baixo")` |
| Criar uma sequência | `np.arange(0, 10, 2)` |
| Ordenar | `np.sort(valores)` |
| Criar uma cópia independente | `valores.copy()` |

**Antes de avançar:** você consegue explicar por que usamos `()` em `sum()`, por que usamos `[]` em um filtro e por que `shape` não tem parênteses?


## 19. Resumão de NumPy

**NumPy é uma biblioteca do Python para cálculos numéricos.** Seu objeto principal é o **array**, que guarda valores em uma ou mais dimensões. Importamos com `import numpy as np`; `np` é o apelido usado para acessar a biblioteca.

### Ideias para lembrar

- **Lista e array:** ambos guardam sequências, permitem índices, fatiamento e `for`. Em uma lista, `* 2` repete a sequência; em um array numérico, dobra cada elemento.
- **Índices:** começam em zero. `[0]` acessa o primeiro elemento; `[-1]`, o último.
- **Fatiamento:** `[início:fim]` inclui o início e exclui o fim.
- **Cálculos:** `array + 5` e `array * 2` aplicam a operação a cada elemento.
- **Comparação:** `array >= 10` devolve uma máscara de `True` e `False`.
- **Filtro:** `array[array >= 10]` seleciona os valores que atendem à condição.
- **Formato:** `shape` descreve o tamanho de cada dimensão; `ndim` conta dimensões; `size` conta todos os elementos; `dtype` informa o tipo dos elementos.
- **Cópia:** use `.copy()` para obter um array independente. Uma atribuição simples não copia o objeto; fatiamentos simples de arrays geralmente compartilham dados.

### Comandos com exemplos e resultados

Considere `a = np.array([10, 20, 30])`.

| Objetivo | Comando | Resultado |
|---|---|---|
| Criar um array | `np.array([10, 20, 30])` | Array com três valores |
| Primeiro valor | `a[0]` | `10` |
| Último valor | `a[-1]` | `30` |
| Dois primeiros | `a[:2]` | `[10 20]` |
| Quantidade de elementos | `a.size` | `3` |
| Formato | `a.shape` | `(3,)` |
| Dimensões | `a.ndim` | `1` |
| Somar 5 a cada valor | `a + 5` | `[15 25 35]` |
| Dobrar os valores | `a * 2` | `[20 40 60]` |
| Somar todos | `np.sum(a)` ou `a.sum()` | `60` |
| Calcular média | `np.mean(a)` | `20.0` |
| Menor valor | `np.min(a)` | `10` |
| Maior valor | `np.max(a)` | `30` |
| Comparar | `a >= 20` | `[False True True]` |
| Filtrar | `a[a >= 20]` | `[20 30]` |
| Escolher rótulos | `np.where(a >= 20, "Alto", "Baixo")` | `['Baixo' 'Alto' 'Alto']` |
| Criar sequência | `np.arange(0, 6, 2)` | `[0 2 4]` |
| Ordenar | `np.sort(np.array([30, 10, 20]))` | `[10 20 30]` |
| Copiar | `a.copy()` | Novo array independente com os mesmos valores |

### Como ler a escrita

| Símbolo ou termo | Significado | Exemplo |
|---|---|---|
| `.` | Acessa algo da biblioteca ou do objeto | `np.array`, `a.shape` |
| `()` | Executa uma função ou método | `a.sum()` |
| `[]` | Cria uma lista ou seleciona valores, dependendo do contexto | `[10, 20]`, `a[0]` |
| `:` | Delimita um trecho em um fatiamento | `a[0:2]` |
| `=` | Guarda um valor em uma variável | `total = a.sum()` |
| `==` | Compara igualdade | `a == 20` |
| Função | Operação chamada com argumentos | `np.mean(a)` |
| Método | Operação acessada pelo objeto | `a.sum()` |
| Atributo | Informação consultada sem parênteses | `a.size` |
| Argumento | Valor passado na chamada | `a` em `np.mean(a)` |
| Retorno | Resultado entregue pela chamada | `20.0` em `np.mean(a)` |

### Uma dimensão e duas dimensões

- `np.array([10, 20, 30])`: uma dimensão, formato `(3,)`.
- `np.array([[10, 20], [30, 40]])`: duas dimensões, formato `(2, 2)`.
- Em uma matriz, `[linha, coluna]` seleciona uma posição. A contagem começa em zero para as duas.
- `len(array)` informa o tamanho da primeira dimensão; `array.size` informa o total de elementos.

### Quando usar?

Use NumPy para conjuntos de números, cálculos por elemento, estatísticas e matrizes. Listas são úteis para sequências gerais; pandas é conveniente para tabelas com nomes de colunas. Essas ferramentas podem trabalhar juntas.

**Roteiro de resolução:** entender o pedido → identificar dados e regra → prever o resultado à mão → escolher o comando → executar → conferir.
